name: pinta-service-public

services:
  backend:
    container_name: ps-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5174:5173'
    networks:
      - database
    restart: unless-stopped
    attach: true

networks:
  database:
    driver: bridge
