name: pinta-service-public

services:
  frontend:
    container_name: ps-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BACKEND_BASE_URL: ${BACKEND_BASE_URL:-http://127.0.0.1:5000}
    ports:
      - '4173:4173'
    restart: unless-stopped
